
version: '3.8'
services:
  cassandra:
    image: cassandra:4.1
    container_name: cassandra
    ports:
      - "9042:9042"
    volumes:
      - cassandra_data:/var/lib/cassandra
    networks:
      - urlshortener_net

  api:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - cassandra
    networks:
      - urlshortener_net

volumes:
  cassandra_data:

networks:
  urlshortener_net: